### ISSUE TITLE
Rainbow six ranked mmr system

### ISSUE THREAD

**Issue by HowsMyHotspot** [r6db/r6db#35]
I have read a lot about the new seasons ranked system but I still don't quite understand it. I am getting plus 15 points each ranked game I win and I'm a gold 3 so its taking me forever to rank up is it possible for me to get more points somehow.

**Comment by asap777** [comment]
After your 10 placement games you will start off in a rank based on how many of those 10 games you won. Winning 7/10 games will place you into Platinum 3.

From then on you will get about 100 points a win or loss because the games uncertainty of your rank is still high. Basically the more games you play the more certain the game is of your placement. The less points you will get for winning and losing. 

So from the sounds of it, if you're still gold 3 and getting 15 points the game pretty much decided where you should be placed. You will have to somehow start winning most of your games to rank up significantly. 

Your other option is to create a new account and play the 10 placement matches again and try to get a higher rank. 

But considering you're gold 3 I would focus on getting better at the game so by the time next season comes around you can get into platinum. I also recommend to play with 5 man squads for communication with players that have equal or greater stats than you for the best chance of winning more games.

**Comment by HowsMyHotspot** [comment]
Alright that really helped me understand it thanks.
