### ISSUE TITLE
Players with identical mmr/uncertainty have the same rank

### ISSUE THREAD

**Issue by LaxisB** [r6db/r6db#5]
this isn't a bug directly, but an interesting point i didn't think about before.  
It might be interesting to think about wether we should actuvely circumvent this or not.

muppet - https://r6db.com/player/ccd28cc4-845e-4726-8cf8-e2cac4de82a2
laxis - https://r6db.com/player/1b50085a-8a20-4ce6-b75f-db6a00e4d718
krum - https://r6db.com/player/102046f7-9a67-4ee7-b569-7bf6c435f2b1
tp - https://r6db.com/player/21829386-1aa9-4d78-805a-4f2c0371a126

we all have rank 1514

**Comment by NaughtyMuppet** [comment]
I didn't think this would happen but I'm fine with this happening

**Comment by NaughtyMuppet** [comment]
https://blog.jooq.org/2014/08/12/the-difference-between-row_number-rank-and-dense_rank/

We use RANK() instead of ROW_NUMBER(), that's why this is happening. If we're going to change it, we'll have to create new materialized views before dropping the old ones. But to be honest I'd rather stay with this system....

**Comment by LaxisB** [comment]
agreed
